// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvWFh781GY1vraOY0KOM5kzFxmOOv90G0',
    appId: '1:748936763477:web:d0f06158179c733e055cdc',
    messagingSenderId: '748936763477',
    projectId: 'absensigurusmpn3',
    authDomain: 'absensigurusmpn3.firebaseapp.com',
    storageBucket: 'absensigurusmpn3.firebasestorage.app',
    measurementId: 'G-J6BWHJK0LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdomwMFwYE4qzFhdsClZjSxy1HvTuZWnU',
    appId: '1:748936763477:android:1825bc6a1a2e24d7055cdc',
    messagingSenderId: '748936763477',
    projectId: 'absensigurusmpn3',
    storageBucket: 'absensigurusmpn3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTrDxVNIU9_JuQ8G3N8IHgs6jT_nlOFzI',
    appId: '1:748936763477:ios:0f9c01c90de3b3ba055cdc',
    messagingSenderId: '748936763477',
    projectId: 'absensigurusmpn3',
    storageBucket: 'absensigurusmpn3.firebasestorage.app',
    iosBundleId: 'com.example.ta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvWFh781GY1vraOY0KOM5kzFxmOOv90G0',
    appId: '1:748936763477:web:738d5735cdfcaf01055cdc',
    messagingSenderId: '748936763477',
    projectId: 'absensigurusmpn3',
    authDomain: 'absensigurusmpn3.firebaseapp.com',
    storageBucket: 'absensigurusmpn3.firebasestorage.app',
    measurementId: 'G-LWHQBTCNV9',
  );
}
